name: common
description: A Dart package that contains common Revision Tool code shared between multiple projects.
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:

  # Network
  dio: ^5.8.0+1

  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Logging
  logger: ^2.5.0

  # Other
  args: ^2.6.0
  path: ^1.9.1
  process_run: ^1.2.2+1
  win32_registry: ^2.0.1
  xml: ^6.5.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  lints: ^5.1.1
  # test: ^1.24.0
