name: common
description: A Dart package that contains common Revision Tool code shared between multiple projects.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:

  # Network
  dio: ^5.7.0

  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Logging
  logger: ^2.4.0

  # Other
  args: ^2.5.0
  path: ^1.9.0
  process_run: ^1.2.0+1
  win32_registry: ^1.1.5
  xml: ^6.5.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  # test: ^1.24.0
