name: revitool
description: A tool to personalize ReviOS to your needs
publish_to: "none"

# The version number defaults to 1.0.0 for easier development and is incremented by the build flags based on the tag
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  slang: ^4.12.1
  slang_flutter: ^4.12.1

  # UI
  fluent_ui: ^4.13.0
  system_theme: ^3.1.2
  flutter_acrylic: ^1.1.4
  fluentui_system_icons: ^1.1.273
  window_plus:
    git:
      # url: https://github.com/melo936/window_plus
      url: https://github.com/alexmercerind/window_plus
  adaptive_palette: 
   git:
      url: https://github.com/melo936/adaptive_palette

  # State management
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

  # Path
  path: ^1.9.1

  # Network
  dio: ^5.9.1

  # Shell
  process_run: ^1.3.0

  # Interactivity with Windows
  win32: ^5.15.0
  win32_registry: ^2.1.0

  # Code generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.10.0

  # Logging
  logger: ^2.6.2

  # Command line
  args: ^2.7.0

  # Routing
  go_router: ^17.1.0

  # Other
  collection: ^1.18.0
  xml: ^6.6.1
  ffi: ^2.2.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.3
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  riverpod_generator: ^4.0.3
  mocktail: ^1.0.4
  slang_build_runner: ^4.12.1

dependency_overrides:
  petitparser: ^7.0.2
  math_expressions: ^3.1.0
  
flutter:
  uses-material-design: false

  assets:
    - additionals/
    - additionals/msstore/
    - additionals/packages/winsxs/
