name: revitool
description: A tool to personalize ReviOS to your needs
publish_to: "none"

# The version number defaults to 1.0.0 for easier development and is incremented by the build flags based on the tag
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Localization
  slang: ^4.11.2
  slang_flutter: ^4.11.0

  # UI
  fluent_ui: ^4.13.0
  system_theme: ^3.1.2
  flutter_acrylic: ^1.1.4
  fluentui_system_icons: ^1.1.273
  window_plus:
    git:
      # url: https://github.com/melo936/window_plus
      url: https://github.com/alexmercerind/window_plus

  # State management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Path
  path: ^1.9.1

  # Network
  dio: ^5.8.0+1

  # Shell
  process_run: ^1.2.4

  # Interactivity with Windows
  win32: ^5.15.0
  win32_registry: ^2.1.0

  # Code generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Logging
  logger: ^2.6.2

  # Command line
  args: ^2.7.0

  # Routing
  go_router: ^17.0.1

  # Other
  collection: ^1.18.0
  xml: ^6.5.0
  ffi: ^2.1.4
  crypto: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.0+1
  mocktail: ^1.0.4
  analysis_server_plugin: ^0.3.3
  slang_build_runner: ^4.11.0
  

flutter:
  uses-material-design: true

  assets:
    - additionals/
    - additionals/msstore/
    - additionals/packages/winsxs/
